# GitHub Actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: master
on:
  - push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: test asdf plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: "golangci-lint version"
